# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import facialDetection_pb2 as facialDetection__pb2


class FacialDetectionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadDetection = channel.stream_unary(
                '/FacialDetection/UploadDetection',
                request_serializer=facialDetection__pb2.Chunk.SerializeToString,
                response_deserializer=facialDetection__pb2.Reply.FromString,
                )


class FacialDetectionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadDetection(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FacialDetectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadDetection': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadDetection,
                    request_deserializer=facialDetection__pb2.Chunk.FromString,
                    response_serializer=facialDetection__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FacialDetection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FacialDetection(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadDetection(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/FacialDetection/UploadDetection',
            facialDetection__pb2.Chunk.SerializeToString,
            facialDetection__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
